version: 2

models:
  - name: dm_yearly_sales_trend_per_property_type
    config:
      contract: 
        enforced: true
    columns:
      - name: property_type
        data_type: string
      - name: list_year
        data_type: int
      - name: avg_sale_amount
        data_type: float
      - name: avg_assessed_value
        data_type: float
      - name: avg_sales_ratio
        data_type: float

  - name: dm_location_per_town
    config:
      contract:
        enforced: true
    columns:
      - name: list_year
        data_type: int
      - name: town
        data_type: string
      - name: location1
        data_type: string
      - name: location2
        data_type: geography
      - name: avg_sale_amount
        data_type: float