version: 2

models:
  - name: dm_median_sales_amount_per_property_type
    config:
      contract: 
        enforced: true
    columns:
      - name: property_type
        data_type: string
      - name: list_year
        data_type: int
      - name: avg_sale_amount
        data_type: float
      - name: avg_assessed_value
        data_type: float
      - name: median_sale_amount
        data_type: float
      - name: median_assessed_value
        data_type: float

  - name: dm_median_sales_amount_per_town
    config:
      contract:
        enforced: true
    columns:
      - name: list_year
        data_type: int
      - name: property_type
        data_type: string
      - name: town
        data_type: string
      - name: location1
        data_type: string
      - name: location2
        data_type: geography
      - name: avg_sale_amount
        data_type: float
      - name: median_sale_amount
        data_type: float
  - name: dm_overall_metrics
    config:
      contract:
        enforced: true
    columns:
      - name: total_volume
        data_type: float
      - name: number_of_sales
        data_type: int
      - name: avg_sale_amount
        data_type: float
      - name: median_sale_amount
        data_type: float
      - name: avg_sales_ratio
        data_type: float