version: 2

models:
  - name: dm_monthly_sales_trend_per_property_type
    config:
      contract: 
        enforced: true
    columns:
      - name: property_type
        data_type: string
      - name: year
        data_type: int
      - name: month
        data_type: int
      - name: list_year
        data_type: int
      - name: avg_sale_amount
        data_type: float
      - name: avg_assessed_value
        data_type: float
      - name: avg_sales_ratio
        data_type: float