version: 2

models:
  - name: dim_dates_recorded
    config:
      contract: 
        enforced: true
    columns:
      - name: date_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
      - name: date
        data_type: date
      - name: year
        data_type: int
      - name: month
        data_type: int
      - name: day
        data_type: int
  
  - name: dim_properties
    config:
      contract: 
        enforced: true
    columns:
      - name: property_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
      - name: property_type
        data_type: string
      - name: residential_type
        data_type: string
      - name: town
        data_type: string
      - name: address
        data_type: string
      - name: location
        data_type: string

  - name: dim_remarks
    config:
      contract:
        enforced: true
    columns:
      - name: remark_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
      - name: assessor_remark
        data_type: string
      - name: opm_remark
        data_type: string
  
  - name: fact_sales
    config:
      contract:
        enforced: true
    columns:
      - name: sale_id
        data_type: int
        constraints:
          - type: not_null 
          - type: primary_key
        tests:
          - unique
      - name: serial_number
        data_type: int
      - name: list_year
        data_type: int
      - name: date_recorded_id
        data_type: string
        constraints:
          - type: not_null 
          - type: foreign_key
            expression: real_estate_sales_db.dim_dates_recorded (date_id)
      - name: property_id
        data_type: string
        constraints:
          - type: not_null 
          - type: foreign_key
            expression: real_estate_sales_db.dim_properties (property_id)
      - name: remark_id
        data_type: string
        constraints:
          - type: not_null 
          - type: foreign_key
            expression: real_estate_sales_db.dim_remarks (remark_id)
      - name: assessed_value
        data_type: float
      - name: sale_amount
        data_type: float
      - name: sales_ratio
        data_type: float
      - name: non_use_code
        data_type: string
