version: 2

sources:
  - name: staging
    database: crack-celerity-435208-v5
    schema: real_estate_sales_db
    tables:
      - name: source_table


models:
  - name: stg_source_table
    config:
      contract: 
        enforced: true
    columns:
      - name: sale_id
        data_type: int
      - name: serial_number
        data_type: int
      - name: list_year
        data_type: int
      - name: date_recorded
        data_type: date
      - name: town
        data_type: string
      - name: address
        data_type: string
      - name: assessed_value
        data_type: float
      - name: sale_amount
        data_type: float
      - name: sales_ratio
        data_type: float
      - name: property_type
        data_type: string
      - name: residential_type
        data_type: string
      - name: non_use_code
        data_type: string
      - name: assessor_remarks
        data_type: string
      - name: opm_remarks
        data_type: string
      - name: location
        data_type: string
